project:
  type: website

website:
  title: "Dylan H. Morris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications
        text: Publications
      - href: post
        text: Blog posts
      - href: contact
        text: Contact

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



