name: "Build and publish site"

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: 
  contents: write
  pages: write

jobs:
  build-and-publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
        
      - name: "Set up Quarto"
        uses: "quarto-dev/quarto-actions/setup@v2"

      - name: "Render and publish"
        uses: "quarto-dev/quarto-actions/publish@v2"
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
